config/routes.rb
Rails.application.routes.draw do
  get 'user/new'
  get 'sessions/new'
  get 'signup', to: 'usersd#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  
  devise_for :users
  root controller: :articles, action: :index
  resources :articles, only: [:show, :new, :create, :edit, :update]
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  add_flash_types :notice

  protect_from_forgery with: :exception

  def configure permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email]) 
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize 
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @artcle = Article.new
  end

  def create
    @article = Article.create(article_params) 
    if @article.persisted?
      redirect_to article_path(@article), notice: 'Your article was successfully created'
    else
      flash[:notice] = @article.errors.full_messages.to_sentence
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated' #if updated redirected back to article + message
    else
      redirect_to edit_article_path, flash[:notice] = @article.errors.full_messages.to_sentence # other stay andshow error message
      render :show
    end
  end
  
  private

  def article_params # only allow title and content. Nothing is ok
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:eamil])
    if user && user.authenticate(params[:pasword])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
  end

  def destroy
    session[:user:id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
  end
end
            

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<br>
<br>
<%= form_with  model: @article, local: true do |form| %>
  <strong><%= form.label :title%></strong>
  <%= form.text_field :title %>
  <strong><%= form.label :content %></strong>
  <%= form.text_area :content %>
  <br>
  <br>
  <%= form.submit 'Update Article'%>
<% end %>
<br>
<%= link_to 'Back Article List', root_path %>

app/views/articles/index.html.erb
<h1>Welcome to Nice News!</h1>
<ul>
  <%= @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %><br />
    </li>
  <% end %>
</ul>
<%= link_to "Create Article", new_article_path%>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path ,local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>
  <%= form.label :content %>
  <%= form.text_area :content %><br><br>
  <%= form.submit 'Create Article' %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<ul>
  <li><%= link_to 'Back To Article List', root_path %></li>
  <li><%= link_to 'Edit this Article', edit_article_path(@article) %></li>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NiceNews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up here", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
    <%= flash[:notice] %>
  </body>
</html>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>